version: "3"
services:
  db:
    image: mariadb:10
    restart: always
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_USER: test_qa
        MYSQL_DATABASE: BACK
        MYSQL_PASSWORD: qa_test

  mock:
    build: vk_api/
    command: python ./mock.py
    ports:
      - "192.168.0.254:5000:5000"
    
  server:
    image: myapp
    command: /app/myapp --config=/home/alex/config.cfg
    restart: always
    links:
      - "db:BACK"
      - "mock:192.168.0.254"
    ports:
      - "192.168.0.254:80:80"
    volumes:
      - /home/alex/dc/server/:/home/alex/
    depends_on:
      - db
      - mock


